CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "user" (
        "id"    INTEGER NOT NULL UNIQUE,
        "name"  TEXT,
        "card_id"       TEXT NOT NULL UNIQUE,
        "enabled"       INTEGER NOT NULL,
        PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "touchLog" (
        "id"    INTEGER NOT NULL UNIQUE,
        "card_id"       TEXT NOT NULL,
        "time"  TEXT NOT NULL,
        "accept"        INTEGER NOT NULL,
        PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "login_user" (
        "id"    INTEGER NOT NULL UNIQUE,
        "name"  TEXT NOT NULL,
        "password"      TEXT NOT NULL,
        "role"  TEXT NOT NULL,
        PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE SPRING_SESSION (
        PRIMARY_ID CHARACTER(36) NOT NULL,
        SESSION_ID CHARACTER(36) NOT NULL,
        CREATION_TIME INTEGER NOT NULL,
        LAST_ACCESS_TIME INTEGER NOT NULL,
        MAX_INACTIVE_INTERVAL INTEGER NOT NULL,
        EXPIRY_TIME INTEGER NOT NULL,
        PRINCIPAL_NAME VARCHAR(100),
        CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);
CREATE TABLE SPRING_SESSION_ATTRIBUTES (
        SESSION_PRIMARY_ID CHAR(36) NOT NULL,
        ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
        ATTRIBUTE_BYTES BLOB NOT NULL,
        CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
        CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
CREATE UNIQUE INDEX "user_cardId_index" ON "user" (
        "card_id"       ASC
);
CREATE TABLE IF NOT EXISTS "physicalLog" (
        "id"    INTEGER NOT NULL UNIQUE,
        "action"        TEXT NOT NULL,
        "time"  TEXT NOT NULL,
        PRIMARY KEY("id" AUTOINCREMENT)
);